# Generated by Django 4.2.7 on 2023-12-09 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.IntegerField()),
                ('destinatario', models.CharField(max_length=30)),
                ('motivo', models.CharField(max_length=30, null=True)),
                ('tipo', models.CharField(max_length=30, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='Clientes.cliente')),
            ],
        ),
    ]
