# Generated by Django 4.2.7 on 2023-12-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transferencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='tipo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
